version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=event_user
      - POSTGRES_PASSWORD=event_pass
      - POSTGRES_DB=event_db
    volumes:
      - event_db:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - event_redis:/data
  app:
    build: .
    ports:
      - '8000:8000'
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - redis
    environment:
      - APP_DB_HOST=db
      - APP_BROKER_URL=redis://redis:6379
  worker:
    build: .
    command: celery -A event_planer worker -c 1
    depends_on:
      - db
      - redis
    environment:
      - APP_DB_HOST=db
      - APP_BROKER_URL=redis://redis:6379
volumes:
  event_db:
    driver: local
  event_redis:
    driver: local